[integration]
marshaler = "json"

[integration.mqtt]
event_topic_template   = "eu433/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template   = "eu433/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template = "eu433/gateway/{{ .GatewayID }}/command/#"

[integration.mqtt.auth.generic]
servers = ["tcp://mosquitto:1883/"]

[backend]
type = "semtech_udp"

[backend.semtech_udp]
udp_bind = ":1700"
